import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, mkdirSync, cpSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  loadConfig, loadSessions, saveSessions, allocatePorts,
  run, runQuiet, slugify,
  sessionUserName, sessionHome, tmuxSessionName,
  userExists, isSyncFresh,
  KON_ENV, REPOS_DIR, SESSIONS_DIR, TEMPLATES_DIR,
  renderTemplate,
} from "./helpers.mjs";
import { cmdSync } from "./session-manage.mjs";

// ── Dev server detection ────────────────────────────────────────────────────

function detectPackageManager(repoPath) {
  if (existsSync(join(repoPath, "bun.lockb")) || existsSync(join(repoPath, "bun.lock")))
    return "bun";
  if (existsSync(join(repoPath, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(repoPath, "yarn.lock"))) return "yarn";
  return "npm";
}

function detectDevCommand(repoPath, pm) {
  try {
    const pkg = JSON.parse(readFileSync(join(repoPath, "package.json"), "utf-8"));
    if (pkg.scripts && pkg.scripts.dev) {
      return `${pm} run dev`;
    }
    if (pkg.scripts && pkg.scripts.start) {
      return `${pm} run start`;
    }
  } catch {}
  return null;
}

function installCommand(pm) {
  switch (pm) {
    case "bun": return "bun install";
    case "pnpm": return "pnpm install --frozen-lockfile";
    case "yarn": return "yarn install --frozen-lockfile";
    default: return "npm ci";
  }
}

// ── Docker helpers ──────────────────────────────────────────────────────────

function dockerAvailable() {
  return existsSync("/usr/bin/docker");
}

// ── Nginx config ────────────────────────────────────────────────────────────

function generateNginxConfig(configName, serverName, domain, port) {
  return `# Auto-generated by kon for: ${configName}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${serverName};

    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;

    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
    proxy_send_timeout 60s;

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`;
}

function applyNginxConfig(configName, serverName, domain, port) {
  mkdirSync("/etc/nginx/sessions", { recursive: true });
  const configPath = `/etc/nginx/sessions/${configName}.conf`;
  writeFileSync(configPath, generateNginxConfig(configName, serverName, domain, port));

  const testResult = runQuiet("nginx -t 2>&1");
  if (testResult.includes("failed")) {
    console.error(`  Nginx config test failed for ${configName}, removing config`);
    runQuiet(`rm -f ${configPath}`);
    return false;
  }
  runQuiet("systemctl reload nginx");
  return true;
}

export function removeNginxConfigs(sessionName) {
  // Remove all nginx configs for this session (main + per-service)
  const configs = runQuiet(`ls /etc/nginx/sessions/ 2>/dev/null`);
  if (!configs) return;
  let removed = false;
  for (const file of configs.split("\n")) {
    if (file === `${sessionName}.conf` || file.endsWith(`-${sessionName}.conf`)) {
      runQuiet(`rm -f /etc/nginx/sessions/${file}`);
      removed = true;
    }
  }
  if (removed) runQuiet("systemctl reload nginx");
}

// ── AI config generation ────────────────────────────────────────────────────

function generateAiConfigs(home, vars) {
  const claudePath = join(TEMPLATES_DIR, "session-claude.md");
  const agentsPath = join(TEMPLATES_DIR, "session-agents.md");

  if (existsSync(claudePath)) {
    writeFileSync(join(home, "CLAUDE.md"), renderTemplate(claudePath, vars));
  }
  if (existsSync(agentsPath)) {
    writeFileSync(join(home, "AGENTS.md"), renderTemplate(agentsPath, vars));
  }
}

// ── Main create command ─────────────────────────────────────────────────────

export function cmdNew(name, flags = {}) {
  if (!name) {
    console.error("Usage: kon new <name> [--creator <who>] [--ssh-key <pubkey>]");
    process.exit(1);
  }

  name = slugify(name);
  const sessions = loadSessions();

  if (sessions[name]) {
    console.error(`Session "${name}" already exists. Use 'kon join ${name}' to attach.`);
    process.exit(1);
  }

  const config = loadConfig();
  const domain = config.domain || "localhost";
  const username = sessionUserName(name);
  const home = sessionHome(name);

  // Sync repos if cache is stale
  if (!isSyncFresh()) {
    console.log("Syncing repos before creating session...");
    cmdSync();
  } else {
    console.log("Repo cache is fresh, skipping sync.");
  }

  console.log(`\nCreating session "${name}"...`);

  // 1. Create linux user (with docker group if available)
  if (!userExists(username)) {
    const groups = "kon-sessions" + (dockerAvailable() ? ",docker" : "");
    run(`useradd -m -s /bin/bash -G ${groups} ${username}`);
    run(`passwd -l ${username}`);
    run(`chmod 700 ${home}`);
  }
  const tmpDir = `/tmp/kon-${name}`;
  mkdirSync(tmpDir, { recursive: true });
  run(`chown ${username}:${username} ${tmpDir}`);
  run(`chmod 700 ${tmpDir}`);

  // 2. Install SSH key if provided
  if (flags.sshKey) {
    const sshDir = join(home, ".ssh");
    mkdirSync(sshDir, { recursive: true });
    writeFileSync(join(sshDir, "authorized_keys"), flags.sshKey.trim() + "\n");
    run(`chown -R ${username}:${username} ${sshDir}`);
    run(`chmod 700 ${sshDir}`);
    run(`chmod 600 ${sshDir}/authorized_keys`);
  }

  // 3. Clone repos (with submodule support)
  const reposBase = join(home, config.repos_dir || "repos");
  mkdirSync(reposBase, { recursive: true });

  for (const repo of config.repos) {
    const dest = join(reposBase, repo.name);
    const source = join(REPOS_DIR, repo.name);

    if (existsSync(source)) {
      console.log(`  Copying ${repo.name} from cache...`);
      cpSync(source, dest, { recursive: true });
      // Initialize submodules if copied from cache
      if (repo.submodules) {
        console.log(`  Initializing submodules for ${repo.name}...`);
        runQuiet(`git -C ${dest} submodule update --init --recursive`);
      }
    } else {
      const cloneFlags = repo.submodules ? " --recurse-submodules" : "";
      console.log(`  Cloning ${repo.name}...`);
      run(`git clone${cloneFlags} ${repo.url} ${dest}`);
    }
  }

  // 4. gh CLI auth
  const ghConfigDir = join(home, ".config", "gh");
  const systemGhConfig = "/opt/kon/.config/gh/hosts.yml";
  if (existsSync(systemGhConfig)) {
    mkdirSync(ghConfigDir, { recursive: true });
    cpSync(systemGhConfig, join(ghConfigDir, "hosts.yml"));
  }

  // 5. Git config
  if (flags.creator) {
    writeFileSync(join(home, ".gitconfig"), `[user]\n\tname = ${flags.creator}\n`);
  }

  // 6. Allocate ports
  const ports = allocatePorts(config, sessions);

  // 7. Install deps for all paths (repo roots, service sub-paths, submodule dirs)
  for (const repo of config.repos) {
    const repoPath = join(reposBase, repo.name);
    const installPaths = new Set();
    installPaths.add(repoPath);

    // Add service sub-paths
    for (const svc of repo.services || []) {
      if (svc.path && svc.path !== ".") {
        installPaths.add(join(repoPath, svc.path));
      }
    }

    // Add submodule dirs
    if (repo.submodules) {
      const subPaths = runQuiet(
        `git -C ${repoPath} submodule foreach --quiet 'echo $toplevel/$sm_path'`
      );
      if (subPaths) {
        subPaths.split("\n").forEach((p) => {
          if (p.trim()) installPaths.add(p.trim());
        });
      }
    }

    for (const installPath of installPaths) {
      if (!existsSync(join(installPath, "package.json"))) continue;
      const pm = detectPackageManager(installPath);
      console.log(`  Installing deps at ${installPath} (${pm})...`);
      runQuiet(`su - ${username} -c "cd ${installPath} && ${installCommand(pm)} 2>&1 | tail -3"`);
    }
  }

  // 8. Start all services across all repos
  const devServers = [];
  let portIndex = 0;
  const hasDocker = dockerAvailable();

  // Create Docker network for this session if any docker services exist
  const hasDockerServices = config.repos.some(
    (r) => (r.services || []).some((s) => s.type === "docker")
  );
  if (hasDockerServices && hasDocker) {
    console.log(`  Creating Docker network kon-${name}...`);
    runQuiet(`docker network create kon-${name} 2>/dev/null`);
  }

  for (const repo of config.repos) {
    const repoPath = join(reposBase, repo.name);
    let services = repo.services || [];

    // Backward compat: if no services defined, auto-detect from package.json
    if (services.length === 0) {
      if (existsSync(join(repoPath, "package.json"))) {
        const pm = detectPackageManager(repoPath);
        const devCmd = repo.devCommand || detectDevCommand(repoPath, pm);
        if (devCmd) {
          services = [{
            label: repo.name,
            path: ".",
            devCommand: devCmd,
            type: "dev",
          }];
        }
      }
    }

    for (const svc of services) {
      const svcPath = svc.path === "." ? repoPath : join(repoPath, svc.path);

      if (svc.type === "docker") {
        if (!hasDocker) {
          console.log(`  Skipping Docker service "${svc.label}" (Docker not installed)`);
          continue;
        }
        console.log(`  Starting Docker service "${svc.label}"...`);
        const cmd = `cd ${svcPath} && COMPOSE_PROJECT_NAME=kon-${name} ${svc.devCommand}`;
        runQuiet(`su - ${username} -c '${cmd}'`);
        devServers.push({ label: svc.label, port: null, type: "docker", repoName: repo.name });
      } else {
        // Standard dev server
        const port = ports[portIndex++];
        const devCmd = svc.devCommand || detectDevCommand(svcPath, detectPackageManager(svcPath));
        if (devCmd) {
          console.log(`  Starting "${svc.label}" on port ${port}...`);
          const logFile = join(tmpDir, `${svc.label}.log`);
          const pidFile = join(tmpDir, `${svc.label}.pid`);
          const cmd = `cd ${svcPath} && PORT=${port} nohup ${devCmd} --port ${port} --host 127.0.0.1 > ${logFile} 2>&1 & echo $! > ${pidFile}`;
          runQuiet(`su - ${username} -c '${cmd}'`);
          devServers.push({
            label: svc.label,
            port,
            type: "dev",
            repoName: repo.name,
            subdomain: svc.subdomain || svc.label,
          });
        }
      }
    }
  }

  // 9. Configure nginx for all dev services
  const httpServers = devServers.filter((s) => s.type === "dev" && s.port);
  if (domain !== "localhost" && httpServers.length > 0) {
    if (httpServers.length === 1) {
      // Single service: use simple session.domain
      console.log(`  Configuring nginx for ${name}.${domain}...`);
      applyNginxConfig(name, `${name}.${domain}`, domain, httpServers[0].port);
    } else {
      // Multiple services: label-session.domain per service
      for (const svc of httpServers) {
        const configName = `${svc.subdomain}-${name}`;
        const serverName = `${svc.subdomain}-${name}.${domain}`;
        console.log(`  Configuring nginx for ${serverName}...`);
        applyNginxConfig(configName, serverName, domain, svc.port);
      }
      // Also set up session.domain pointing to the first service
      console.log(`  Configuring nginx for ${name}.${domain} (primary)...`);
      applyNginxConfig(name, `${name}.${domain}`, domain, httpServers[0].port);
    }
  }

  // 10. Bashrc additions
  const bashrcAddition = `
# kon session
export KON_SESSION="${name}"
export KON_DOMAIN="${domain}"
export REPOS_DIR="${reposBase}"
export KON_PORTS="${ports.join(",")}"
export TMPDIR="${tmpDir}"
${existsSync(KON_ENV) ? `set -a; source ${KON_ENV}; set +a` : ""}
cd "${reposBase}"
`;
  const bashrcPath = join(home, ".bashrc");
  const existing = existsSync(bashrcPath) ? readFileSync(bashrcPath, "utf-8") : "";
  if (!existing.includes("KON_SESSION")) {
    writeFileSync(bashrcPath, existing + bashrcAddition);
  }

  // 11. Generate AI config files (CLAUDE.md + AGENTS.md)
  const repoListStr = config.repos
    .map((r) => `- \`${reposBase}/${r.name}\` (${r.url})`)
    .join("\n");

  const serviceListStr = devServers
    .map((s) => {
      if (s.type === "docker") return `- **${s.label}** (docker) — ${s.repoName}`;
      const url = httpServers.length === 1
        ? `https://${name}.${domain}`
        : `https://${s.subdomain}-${name}.${domain}`;
      return `- **${s.label}** — port ${s.port} — ${url}`;
    })
    .join("\n");

  generateAiConfigs(home, {
    name,
    username,
    domain,
    home,
    reposDir: reposBase,
    repoList: repoListStr,
    serviceList: serviceListStr,
    portCount: String(ports.length),
    portList: ports.join(", "),
  });

  // Also copy CLAUDE.md into each repo for context
  for (const repo of config.repos) {
    const repoClaudePath = join(reposBase, repo.name, "CLAUDE.md");
    if (!existsSync(repoClaudePath)) {
      cpSync(join(home, "CLAUDE.md"), repoClaudePath);
    }
    const repoAgentsPath = join(reposBase, repo.name, "AGENTS.md");
    if (!existsSync(repoAgentsPath)) {
      cpSync(join(home, "AGENTS.md"), repoAgentsPath);
    }
  }

  // 12. Set ownership
  run(`chown -R ${username}:${username} ${home}`);

  // 13. Cgroup resource limits
  const sliceContent = `[Slice]\nMemoryMax=2G\nMemoryHigh=1536M\nCPUQuota=200%\nTasksMax=512\n`;
  const slicePath = `/etc/systemd/system/kon-${name}.slice`;
  writeFileSync(slicePath, sliceContent);
  runQuiet("systemctl daemon-reload");

  // 14. Save session metadata
  sessions[name] = {
    created_at: new Date().toISOString(),
    creator: flags.creator || null,
    ports,
    services: devServers.map((s) => ({
      label: s.label,
      port: s.port,
      type: s.type,
      repoName: s.repoName,
      url: s.type === "docker" ? null
        : httpServers.length === 1
          ? `https://${name}.${domain}`
          : `https://${s.subdomain}-${name}.${domain}`,
    })),
    dev_port: httpServers[0]?.port || ports[0], // backward compat
    domain,
    url: `https://${name}.${domain}`,
    slice: `kon-${name}.slice`,
  };
  saveSessions(sessions);

  // 15. Start tmux session and attach
  const tmuxName = tmuxSessionName(name);
  run(
    `systemd-run --slice=kon-${name}.slice --uid=$(id -u ${username}) --gid=$(id -g ${username}) --setenv=HOME=${home} --setenv=USER=${username} -p WorkingDirectory=${reposBase} -- tmux new-session -d -s ${tmuxName}`,
    { quiet: true }
  );

  console.log(`\nSession "${name}" created.`);
  console.log(`  User:    ${username}`);
  console.log(`  Home:    ${home}`);
  console.log(`  Ports:   ${ports.slice(0, portIndex).join(", ") || "none"}`);
  if (httpServers.length === 1) {
    console.log(`  Dev:     https://${name}.${domain}`);
  } else if (httpServers.length > 1) {
    console.log(`  Services:`);
    for (const svc of devServers) {
      if (svc.type === "docker") {
        console.log(`    ${svc.label}: docker (${svc.repoName})`);
      } else {
        const url = httpServers.length === 1
          ? `https://${name}.${domain}`
          : `https://${svc.subdomain}-${name}.${domain}`;
        console.log(`    ${svc.label}: ${url} (port ${svc.port})`);
      }
    }
  }
  if (flags.creator) console.log(`  Creator: ${flags.creator}`);
  console.log(`  Tmux:    ${tmuxName}`);
  console.log(`\nAttaching to tmux session...`);

  const child = spawn("su", ["-", username, "-c", `tmux attach-session -t ${tmuxName}`], {
    stdio: "inherit",
  });
  child.on("exit", (code) => process.exit(code || 0));
}
