import { spawn } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, mkdirSync, cpSync, readdirSync } from "node:fs";
import { join } from "node:path";
import {
  loadConfig, loadSessions, saveSessions, allocatePorts,
  run, runQuiet, slugify,
  sessionUserName, sessionHome, tmuxSessionName,
  userExists, isSyncFresh,
  KON_ENV, REPOS_DIR, SESSIONS_DIR, TEMPLATES_DIR,
  renderTemplate,
} from "./helpers.mjs";
import { cmdSync } from "./session-manage.mjs";

// ── Dev server detection ────────────────────────────────────────────────────

function detectPackageManager(repoPath) {
  if (existsSync(join(repoPath, "bun.lockb")) || existsSync(join(repoPath, "bun.lock")))
    return "bun";
  if (existsSync(join(repoPath, "pnpm-lock.yaml"))) return "pnpm";
  if (existsSync(join(repoPath, "yarn.lock"))) return "yarn";
  return "npm";
}

function detectDevCommand(repoPath, pm) {
  try {
    const pkg = JSON.parse(readFileSync(join(repoPath, "package.json"), "utf-8"));
    if (pkg.scripts && pkg.scripts.dev) {
      return `${pm} run dev`;
    }
    if (pkg.scripts && pkg.scripts.start) {
      return `${pm} run start`;
    }
  } catch {}
  return null;
}

function installCommand(pm) {
  switch (pm) {
    case "bun": return "bun install";
    case "pnpm": return "pnpm install --frozen-lockfile";
    case "yarn": return "yarn install --frozen-lockfile";
    default: return "npm ci";
  }
}

// ── Nginx config ────────────────────────────────────────────────────────────

function generateNginxConfig(sessionName, domain, port) {
  return `# Auto-generated by kon for session: ${sessionName}
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${sessionName}.${domain};

    ssl_certificate /etc/letsencrypt/live/${domain}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;

    proxy_connect_timeout 10s;
    proxy_read_timeout 300s;
    proxy_send_timeout 60s;

    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
`;
}

function applyNginxConfig(sessionName, domain, port) {
  mkdirSync("/etc/nginx/sessions", { recursive: true });
  const configPath = `/etc/nginx/sessions/${sessionName}.conf`;
  writeFileSync(configPath, generateNginxConfig(sessionName, domain, port));

  const testResult = runQuiet("nginx -t 2>&1");
  if (testResult.includes("failed")) {
    console.error("  Nginx config test failed, removing config");
    runQuiet(`rm -f ${configPath}`);
    return false;
  }
  runQuiet("systemctl reload nginx");
  return true;
}

export function removeNginxConfig(sessionName) {
  const configPath = `/etc/nginx/sessions/${sessionName}.conf`;
  if (existsSync(configPath)) {
    runQuiet(`rm -f ${configPath}`);
    runQuiet("systemctl reload nginx");
  }
}

// ── AI config generation ────────────────────────────────────────────────────

function generateAiConfigs(home, vars) {
  const claudePath = join(TEMPLATES_DIR, "session-claude.md");
  const agentsPath = join(TEMPLATES_DIR, "session-agents.md");

  if (existsSync(claudePath)) {
    writeFileSync(join(home, "CLAUDE.md"), renderTemplate(claudePath, vars));
  }
  if (existsSync(agentsPath)) {
    writeFileSync(join(home, "AGENTS.md"), renderTemplate(agentsPath, vars));
  }
}

// ── Main create command ─────────────────────────────────────────────────────

export function cmdNew(name, flags = {}) {
  if (!name) {
    console.error("Usage: kon new <name> [--creator <who>] [--ssh-key <pubkey>]");
    process.exit(1);
  }

  name = slugify(name);
  const sessions = loadSessions();

  if (sessions[name]) {
    console.error(`Session "${name}" already exists. Use 'kon join ${name}' to attach.`);
    process.exit(1);
  }

  const config = loadConfig();
  const domain = config.domain || "localhost";
  const username = sessionUserName(name);
  const home = sessionHome(name);

  // Sync repos if cache is stale
  if (!isSyncFresh()) {
    console.log("Syncing repos before creating session...");
    cmdSync();
  } else {
    console.log("Repo cache is fresh, skipping sync.");
  }

  console.log(`\nCreating session "${name}"...`);

  // 1. Create linux user
  if (!userExists(username)) {
    run(`useradd -m -s /bin/bash -G kon-sessions ${username}`);
    run(`passwd -l ${username}`);
    run(`chmod 700 ${home}`);
  }
  const tmpDir = `/tmp/kon-${name}`;
  mkdirSync(tmpDir, { recursive: true });
  run(`chown ${username}:${username} ${tmpDir}`);
  run(`chmod 700 ${tmpDir}`);

  // 2. Install SSH key if provided
  if (flags.sshKey) {
    const sshDir = join(home, ".ssh");
    mkdirSync(sshDir, { recursive: true });
    writeFileSync(join(sshDir, "authorized_keys"), flags.sshKey.trim() + "\n");
    run(`chown -R ${username}:${username} ${sshDir}`);
    run(`chmod 700 ${sshDir}`);
    run(`chmod 600 ${sshDir}/authorized_keys`);
  }

  // 3. Clone repos
  const reposBase = join(home, config.repos_dir || "repos");
  mkdirSync(reposBase, { recursive: true });

  for (const repo of config.repos) {
    const dest = join(reposBase, repo.name);
    const source = join(REPOS_DIR, repo.name);

    if (existsSync(source)) {
      console.log(`  Copying ${repo.name} from cache...`);
      cpSync(source, dest, { recursive: true });
    } else {
      console.log(`  Cloning ${repo.name}...`);
      run(`git clone ${repo.url} ${dest}`);
    }
  }

  // 4. gh CLI auth
  const ghConfigDir = join(home, ".config", "gh");
  const systemGhConfig = "/opt/kon/.config/gh/hosts.yml";
  if (existsSync(systemGhConfig)) {
    mkdirSync(ghConfigDir, { recursive: true });
    cpSync(systemGhConfig, join(ghConfigDir, "hosts.yml"));
  }

  // 5. Git config
  if (flags.creator) {
    writeFileSync(join(home, ".gitconfig"), `[user]\n\tname = ${flags.creator}\n`);
  }

  // 6. Allocate ports
  const ports = allocatePorts(config, sessions);
  const devPort = ports[0]; // First port is for the primary dev server

  // 7. Install deps + detect dev server for each repo
  const repoDevInfo = [];
  for (const repo of config.repos) {
    const repoPath = join(reposBase, repo.name);
    if (!existsSync(join(repoPath, "package.json"))) {
      repoDevInfo.push({ name: repo.name, pm: null, devCmd: null });
      continue;
    }

    const pm = detectPackageManager(repoPath);
    const devCmd = repo.devCommand || detectDevCommand(repoPath, pm);

    console.log(`  Installing deps for ${repo.name} (${pm})...`);
    runQuiet(`su - ${username} -c "cd ${repoPath} && ${installCommand(pm)} 2>&1 | tail -3"`);

    repoDevInfo.push({ name: repo.name, pm, devCmd, path: repoPath });
  }

  // 8. Start dev server for the primary repo
  const primaryRepo = repoDevInfo[0];
  let devServerStarted = false;
  if (primaryRepo && primaryRepo.devCmd) {
    console.log(`  Starting dev server for ${primaryRepo.name} on port ${devPort}...`);
    const cmd = `cd ${primaryRepo.path} && PORT=${devPort} nohup ${primaryRepo.devCmd} --port ${devPort} --host 127.0.0.1 > /tmp/kon-${name}/dev-server.log 2>&1 & echo $! > /tmp/kon-${name}/dev-server.pid`;
    runQuiet(`su - ${username} -c '${cmd}'`);
    devServerStarted = true;
  }

  // 9. Configure nginx for session subdomain
  if (devServerStarted && domain !== "localhost") {
    console.log(`  Configuring nginx for ${name}.${domain}...`);
    applyNginxConfig(name, domain, devPort);
  }

  // 10. Bashrc additions
  const bashrcAddition = `
# kon session
export KON_SESSION="${name}"
export KON_DOMAIN="${domain}"
export REPOS_DIR="${reposBase}"
export KON_PORTS="${ports.join(",")}"
export TMPDIR="${tmpDir}"
${existsSync(KON_ENV) ? `set -a; source ${KON_ENV}; set +a` : ""}
cd "${reposBase}"
`;
  const bashrcPath = join(home, ".bashrc");
  const existing = existsSync(bashrcPath) ? readFileSync(bashrcPath, "utf-8") : "";
  if (!existing.includes("KON_SESSION")) {
    writeFileSync(bashrcPath, existing + bashrcAddition);
  }

  // 11. Generate AI config files (CLAUDE.md + AGENTS.md)
  const repoListStr = config.repos
    .map((r) => `- \`${reposBase}/${r.name}\` (${r.url})`)
    .join("\n");

  generateAiConfigs(home, {
    name,
    username,
    domain,
    home,
    reposDir: reposBase,
    repoList: repoListStr,
    portCount: String(ports.length),
    portList: ports.join(", "),
  });

  // Also copy CLAUDE.md into each repo for context
  for (const repo of config.repos) {
    const repoClaudePath = join(reposBase, repo.name, "CLAUDE.md");
    if (!existsSync(repoClaudePath)) {
      cpSync(join(home, "CLAUDE.md"), repoClaudePath);
    }
    const repoAgentsPath = join(reposBase, repo.name, "AGENTS.md");
    if (!existsSync(repoAgentsPath)) {
      cpSync(join(home, "AGENTS.md"), repoAgentsPath);
    }
  }

  // 12. Set ownership
  run(`chown -R ${username}:${username} ${home}`);

  // 13. Cgroup resource limits
  const sliceContent = `[Slice]\nMemoryMax=2G\nMemoryHigh=1536M\nCPUQuota=200%\nTasksMax=512\n`;
  const slicePath = `/etc/systemd/system/kon-${name}.slice`;
  writeFileSync(slicePath, sliceContent);
  runQuiet("systemctl daemon-reload");

  // 14. Save session metadata
  sessions[name] = {
    created_at: new Date().toISOString(),
    creator: flags.creator || null,
    ports,
    dev_port: devPort,
    domain,
    url: `https://${name}.${domain}`,
    slice: `kon-${name}.slice`,
  };
  saveSessions(sessions);

  // 15. Start tmux session and attach
  const tmuxName = tmuxSessionName(name);
  run(
    `systemd-run --slice=kon-${name}.slice --uid=$(id -u ${username}) --gid=$(id -g ${username}) --setenv=HOME=${home} --setenv=USER=${username} -p WorkingDirectory=${reposBase} -- tmux new-session -d -s ${tmuxName}`,
    { quiet: true }
  );

  console.log(`\nSession "${name}" created.`);
  console.log(`  User:    ${username}`);
  console.log(`  Home:    ${home}`);
  console.log(`  Ports:   ${ports.join(", ")}`);
  if (devServerStarted) {
    console.log(`  Dev:     https://${name}.${domain}`);
  }
  if (flags.creator) console.log(`  Creator: ${flags.creator}`);
  console.log(`  Tmux:    ${tmuxName}`);
  console.log(`\nAttaching to tmux session...`);

  const child = spawn("su", ["-", username, "-c", `tmux attach-session -t ${tmuxName}`], {
    stdio: "inherit",
  });
  child.on("exit", (code) => process.exit(code || 0));
}
