---
- name: Provision server
  hosts: vps
  become: true
  vars:
    deploy_root: /var/www/{{ domain }}
    certbot_email: admin@{{ domain }}

  roles:
    - common
    - nginx
    - certbot
    - sessions
